### ISSUE TITLE
Error: Cannot use namespace 'Point' as a type.

### ISSUE THREAD

**Issue by carcigenicate** [mapbox/mapbox-gl-draw#1393]
Mapbox GL Version: 3.6.0
Mapbox GL Draw Version: 1.5.0

After upgrading from Mapbox GL 3.4.0 to 3.6.0, I began getting an error that I've been unable to resolve:

```
Error: node_modules/@types/mapbox__vector-tile/index.d.ts:16:21 - error TS2709: Cannot use namespace 'Point' as a type.

16     loadGeometry(): Point[][];
                       ~~~~~
```
It's failing internally in the `mapbox__vector-tile` library that Mapbox imports. This only fails though if Mapbox GL Draw is also included in the project. Otherwise, it works fine.

MCVE:

`package.json`
```json
{
  "name": "map-mcve",
  "main": "index.js",
  "dependencies": {
    "mapbox-gl": "3.6.0",
    "@mapbox/mapbox-gl-draw": "^1.5.0"
  },
  "devDependencies": {
    "typescript": "^5.8.3"
  }
}
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "strict": true,
  }
}
```

And then import `mapbox-gl` into a `index.ts` and run `tsc`.

I was [advised to post an issue here](https://github.com/mapbox/mapbox-gl-js/issues/13203#issuecomment-2826697027), since this might be fixed be an eventualy Typescript migration.

I also have a [SO question open](https://stackoverflow.com/questions/79560829/cannot-use-namespace-point-as-a-type-when-updating-mapbox-gl?noredirect=1#comment140359715_79560829) for more context.
